version: '2'
services:
    api-db:
        image: mysql:latest
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=billingapp
            - MYSQL_USER=user1
            - MYSQL_PASSWORD=pw1
            - MYSQL_ROOT_HOST=%
        volumes:
            - ~/billingapp/db:/var/lib/mysql
    mysqldumper:
        image: ubuntu
        links:
            - "api-db:database"
        entrypoint: ["/root/entry.sh"]
        volumes:
            - ~/goauth/:/root
        
